---
 - name: install apache
   yum:
     name: ['httpd', 'policycoreutils-python-2.5-34.el7.x86_64']
     state: present

 - name: copy balancer config
   template:
     src: balancer.conf.j2
     dest: /etc/httpd/conf.d/balancer.conf

 - name: firewall enable service
   firewalld:
     service: http
     permanent: true
     zone: public
     state: enabled
     immediate: yes

 - name: set sebool for apache
   seboolean:
     name: httpd_can_network_connect
     state: yes
     persistent: yes

 - name: start apache
   service: 
     daemon-reload: yes  
     name: httpd 
     state: started
     enabled: yes

# tasks file for balancer
