--- 
 - name: copy config file
   copy:
     src: my.cnf
     dest: /etc/my.cnf

 - name: restart mdb
   service:
     name: mariadb
     state: restarted 

 - name: delete anon user
   mysql_user:
       user: ""
       host: [ '{{ ansible_hostname}}', 'localhost' ] 
       state: absent

 - name: remove test db
   mysql_db:
       db: 'test'
       state: absent

 - name: create db
   mysql_db:
     db: "{{ dbname }}"
     encoding: utf8
     collation: utf8_bin
     state: present

 - name: create user
   mysql_user:
     name: "{{ dbuser }}"
     password: "{{ dbpass }}"
     host: "{{ hostvars['zabbix']['ansible_host'] }}"
     priv: "zabbix.*:ALL"
     state: present

 - name: add zabbix host
   lineinfile:
     path: /etc/hosts
     line: "{{ hostvars['zabbix']['ansible_host'] }} zabbix"
     state: present
     
 - name: copy import script
   copy: 
     src: create.sql.gz
     dest: /tmp/create.sql.gz
     
 - name: import zabbix db
   mysql_db:
     db: "{{ dbname }}"
     login_user: root
     login_password: ''
     login_host: "localhost"
     state: import
     target: /tmp/create.sql.gz

# tasks file for conf_mdb
