---
 - name: install pckgs
   yum:
     name: epel-release
     state: present
 
 - name: zabbix key
   rpm_key:
     key: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX
     state: present

 - name: zabbix repo
   yum: 
     name: "https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm"
     state: present       

 - name: zabbix pckgs
   yum:
     name: ['zabbix-sender', 'zabbix-agent'] 
     state: present

 - name: enable firewall
   firewalld:
     port: 10050/tcp
     zone: public
     permanent: yes
     state: enabled
     immediate: yes

 - name: firewall for jmx   
   firewalld:
     port: 12345/tcp
     zone: public
     permanent: yes
     state: enabled
     immediate: yes
   when: inventory_hostname in groups["app"]

 - name: config agent
   template:
     src: zabbix_agentd.conf.j2
     dest: /etc/zabbix/zabbix_agentd.conf
  
 - name: start service
   service:
     name: zabbix-agent
     state: restarted
     enabled: yes



# tasks file for zbbx_agent
